---
title: "Tugas Kuliah"
author: "Abdullah' Ammar Rabbaniyyin_M0401241066"
date: "2026-09-01"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r}
library(dplyr)
library(forecast)
library(graphics)
library(TTR)
library(TSA)
```

```{r}
library(readxl)
df <- read.csv("D:\\Mine\\Kuliah Journey\\Semester 5\\MPDW\\mpdw_066\\Pertemuan 2\\Kuliah\\ipm_panel_wide_2010_2021.csv")
head(df)
```

```{r}
library(tidyr)
data_aceh <- df %>% filter(Provinsi == "ACEH") %>%
  pivot_longer (
    cols = starts_with("X"),
    names_to = "Tahun",
    values_to = "Nilai"
  )
data_aceh
```

# Eksplorasi

```{r}
str(data_aceh)
```

```{r}
data_aceh <- data_aceh %>%
  mutate(Tahun = as.numeric(sub("X", "", Tahun)))
data_aceh
```

```{r}
library(rio)
View(data_aceh)
dim(data_aceh)
```

```{r}
aceh.ts <- ts(
  data_aceh$Nilai,
  start = min(data_aceh$Tahun),
  frequency = 1
)
```

```{r}
autoplot(aceh.ts)
```

# Uji Autokorelasi
## Box test

```{r}
Box.test(aceh.ts, lag = 2, type = "Ljung-Box")
Box.test(aceh.ts, lag = 3, type = "Ljung-Box")
Box.test(aceh.ts, lag = 4, type = "Ljung-Box")
```

## ACF

```{r}
acf(aceh.ts)
```

```{r}
ggAcf(aceh.ts)
```

## DW-Test

```{r}
library(lmtest)

model <- lm(Nilai ~ Tahun, data = data_aceh)
dwtest(model)
```

# Penanganan
## Cochrane-Orcutt
### Fungsi

```{r}
library(orcutt)
modelCO<-cochrane.orcutt(model)
modelCO
```

### Transformasi Manual

```{r}
rho<- modelCO$rho
rho
```

```{r}
y <- data_aceh$Nilai
x <- data_aceh$Tahun
y.transformed <- y[-1] - rho * y[-length(y)]
x.transformed <- x[-1] - rho * x[-length(x)]
model.t <- lm(y.transformed ~ x.transformed)

summary(model.t)
```

```{r}
dwtest(model.t)
dwtest(modelCO)
```

## Hildreth-Lu

```{r}
library(HoRM)
hildreth.lu.func<- function(r, model){
  x <- model.matrix(model)[,-1]
  y <- model.response(model.frame(model))
  n <- length(y)
  t <- 2:n
  y <- y[t]-r*y[t-1]
  x <- x[t]-r*x[t-1]
  
  return(lm(y~x))
}
```

```{r}
r <- c(seq(0.1,0.9, by= 0.1))
tab <- data.frame("rho" = r, "SSE" = sapply(r, function(i){deviance(hildreth.lu.func(i, model))}))
round(tab, 4)
```

```{r}
rOpt <- seq(0.4,0.6, by= 0.001)
tabOpt <- data.frame("rho" = rOpt, "SSE" = sapply(rOpt, function(i){deviance(hildreth.lu.func(i, model))}))
head(tabOpt[order(tabOpt$SSE),])
```

### Plot

```{r}
par(mfrow = c(1,1))
plot(tab$SSE ~ tab$rho , type = "l", xlab = "Rho", ylab = "SSE")
abline(v = tabOpt[tabOpt$SSE==min(tabOpt$SSE),"rho"], lty = 2, col="red",lwd=2)
text(x=0.535, y=0.3096072, labels = "rho=0.535", cex = 0.8)
```

```{r}
modelHL <- hildreth.lu.func(0.535, model)
summary(modelHL)
```

```{r}
dwtest(modelHL)
```

# Perbandingan

```{r}
sseModelawal <- anova(model)$`Sum Sq`[-1]
sseModelCO <- anova(model.t)$`Sum Sq`[-1]
sseModelHL <- anova(modelHL)$`Sum Sq`[-1]
mseModelawal <- sseModelawal/length(y)
mseModelCO <- sseModelCO/length(y)
mseModelHL <- sseModelHL/length(y)
akurasi <- matrix(c(sseModelawal,sseModelCO,sseModelHL,
                    mseModelawal,mseModelCO,mseModelHL),nrow=2,ncol=3,byrow = T)
colnames(akurasi) <- c("Model Awal", "Model Cochrane-Orcutt", "Model Hildreth-Lu")
row.names(akurasi) <- c("SSE","MSE")
akurasi
```

