---
title: "Tugas Kuliah"
author: "Abdullah' Ammar Rabbaniyyin_M0401241066"
date: "2026-09-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r}
library(dplyr)
library(forecast)
library(graphics)
library(TTR)
library(TSA)
```

```{r}
library(readxl)
df <- read.csv("D:\\Mine\\Kuliah Journey\\Semester 5\\MPDW\\mpdw_066\\Pertemuan 2\\Kuliah\\ipm_panel_wide_2010_2021.csv")
head(df)
```

```{r}
library(tidyr)
data_aceh <- df %>% filter(Provinsi == "ACEH") %>%
  pivot_longer (
    cols = starts_with("X"),
    names_to = "Tahun",
    values_to = "Nilai"
  )
data_aceh
```

# Eksplorasi

```{r}
str(data_aceh)
```

```{r}
data_aceh <- data_aceh %>%
  mutate(Tahun = as.numeric(sub("X", "", Tahun)))
data_aceh
```

```{r}
library(rio)
View(data_aceh)
dim(data_aceh)
```

```{r}
aceh.ts <- ts(
  data_aceh$Nilai,
  start = min(data_aceh$Tahun),
  frequency = 1
)
```

```{r}
autoplot(aceh.ts)
```

# Uji Autokorelasi
## Box test

```{r}
Box.test(aceh.ts, lag = 2, type = "Ljung-Box")
Box.test(aceh.ts, lag = 3, type = "Ljung-Box")
Box.test(aceh.ts, lag = 4, type = "Ljung-Box")
```

## ACF

```{r}
acf(aceh.ts)
```

```{r}
ggAcf(aceh.ts)
```

## DW-Test

```{r}
library(lmtest)

model <- lm(Nilai ~ Tahun, data = data_aceh)
dwtest(model)
```

# Penanganan
## Cochrane-Orcutt

```{r}
library(orcutt)
install.packages("orcutt")
```

